### ISSUE TITLE
TW Timelines shows wrong link in Library Information box

### ISSUE THREAD

**Issue by cblte** [kookma/TW-PluginLibrary#1]
When looking through the library in an active TiddlyWiki I recognized that the link to the demo and the github repo of the TW-Timelines is point to `https://kookma.github.io/TW-???/` which is not existing. I found the code in this file

https://github.com/kookma/TW-PluginLibrary/blob/main/docs/library/recipes/library/tiddlers/%2524%253A%252Fplugins%252Fkookma%252Ftimelines.json

Links should point to https://github.com/kookma/TW-Timelines and https://kookma.github.io/TW-Timelines/

**Comment by kookma** [comment]
Corrected in Timelines 1.3.0

Thank you for reporting this issue.
